name: Make deploy to server

on:
  push:
    branches:
      - main
  
jobs:
  # パッケージのインストールとビルド
  build_sync:
    name: Package install & Build
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
           node-version: '16'
           cache: 'npm'
      - name: npm install
        run: |
            npm ci
            npm run build --if-present
      - name: AWS configure credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: S3 sync
        run: aws s3 sync ~/dist/ ${{ secrets.AWS_S3_BUCKET_NAME }} --delete
